### ISSUE TITLE
Fixed Skin Changer, Compiled!

### ISSUE THREAD

**Issue by CreativeHell** [B3akers/LeagueSkinChanger#101]
Link: https://anonfiles.com/T9C9i38eu4/LeagueSkinChanger.v11.5_rar

compiled and fixed.

**Comment by 6oody** [comment]
does it works after akshan relase?

**Comment by 6oody** [comment]
![image](https://user-images.githubusercontent.com/42409047/126741359-b062c41e-5bf5-4c28-b21d-807d0fe6c6a7.png)
![image](https://user-images.githubusercontent.com/42409047/126741390-21095076-429e-41c6-9e87-ce6fc4fecab8.png)

**Comment by codexJoin** [comment]
It's false/positive. Because dll_injector.

**Comment by CreativeHell** [comment]
yes it works after akshan release, and that are false positive because of the injector.
