### ISSUE TITLE
cannot bring up the menu

### ISSUE THREAD

**Issue by dxxxxy** [B3akers/LeagueSkinChanger#105]
Injector says `[+] Injected successfully!`. However pressing <kbd>Insert</kbd> does nothing.

**Comment by OktarPwnar** [comment]
Because you need to update offets. Check under issues - if you have a visual studio you can edit the given data within 10 sec and compile it up yourself :)

edit : 

here from one of our contributors, what to do : 

> Update these sigs:
> Open autoupdater.cpp and replace SkinId, and characterdatastack_update to these:
> 
> SkinID: 80 BE ? ? ? ? ? 75 4D 0F 31 33 C9 66 C7 86 ? ? ? ? ? ? 89 44 24 18 33 FF
> CharacterDataStack_Update = 83 EC 2C 53 56 57 8D 44 24 28

**Comment by dxxxxy** [comment]
> Because you need to update offets. Check under issues - if you have a visual studio you can edit the given data within 10 sec and compile it up yourself :)
> 
> edit :
> 
> here from one of our contributors, what to do :
> 
> > Update these sigs:
> > Open autoupdater.cpp and replace SkinId, and characterdatastack_update to these:
> > SkinID: 80 BE ? ? ? ? ? 75 4D 0F 31 33 C9 66 C7 86 ? ? ? ? ? ? 89 44 24 18 33 FF
> > CharacterDataStack_Update = 83 EC 2C 53 56 57 8D 44 24 28

aah thats a shame, i uninstalled it not long ago, i guess i have to wait till dev updates them?

**Comment by OktarPwnar** [comment]
You can do either that or you take a risk and download updated version. Check issues where someone posted it. But of course it on your own risk. You can always go for trial visual studio and update it yourself. This shit (almost) changes every major patch so it's handy to have it :).

Also there is a guy who did fork of this and 'redeveloping' it (also under issues somewhere)

Cheers

**Comment by dxxxxy** [comment]
> You can do either that or you take a risk and download updated version. Check issues where someone posted it. But of course it on your own risk. You can always go for trial visual studio and update it yourself. This shit (almost) changes every major patch so it's handy to have it :).
> 
> Also there is a guy who did fork of this and 'redeveloping' it (also under issues somewhere)
> 
> Cheers

alright, thanks for the fast response. have a great day

**Comment by dxxxxy** [comment]
so uh i replaced the offsets and now i crash everytime it injects

**Comment by OktarPwnar** [comment]
Try to :
- restart your pc 
- run .exe as administrator

extra : 
- make sure you are using newly compiled files and not previous ones
- make sure you did correct editing - even extra space (it's a char for computer after all) can fuck it up ... be really extra careful here

**Comment by dxxxxy** [comment]
try everything, even tried using a fork of this which improved the situation by not making me immediately crash, but crash later in 3mins. everytime the error in the injector is "failed to alloc space"

**Comment by OktarPwnar** [comment]
Weird. I cannot help you at this point on because it works for me - did not really sink into this, just using it.

Also checked it out right now in custom game just to make sure i am not trolling you and it works. I'm sorry mate.

**Comment by OktarPwnar** [comment]
Btw ... even for me it says : [-] Failed to alloc space! after every game ... but ingame it's ok - did you try to press INSERT?

**Comment by dxxxxy** [comment]
> Btw ... even for me it says : [-] Failed to alloc space! after every game ... but ingame it's ok - did you try to press INSERT?

no it instantly crashes when everyone spawns (after 100% loading)

**Comment by dxxxxy** [comment]
but i have a question, when are you supposed to inject? i just keep injector open all the time and it injects by itself after champ select when the game starts loading

**Comment by dxxxxy** [comment]
misclick

**Comment by OktarPwnar** [comment]
You are supposed to have it open for nonstop. Then it will detect the game and inject - after the game it will say failed to alloc ... and when you go another game it will say successfully injected etc. 
So you are 100% sure you download fork .zip package with executables and ran .exe as administrator and it does not work?
Are you using windows 10 or any other os? It works on win10 - really have zero clue why would it crash.
Delete everything in temp folder / restart pc ... dunno what the hack could cause that tbh.

**Comment by codexJoin** [comment]
> misclick

Maybe you replaced the sigs to change are always above the defined name, never below

**Comment by dxxxxy** [comment]
![image](https://user-images.githubusercontent.com/42523606/127689754-f4a4d6aa-b39e-44f7-9981-c361e903503d.png)
these are how my sigs look, and yes im using win10

**Comment by codexJoin** [comment]
You changed data stack.
You need to chamge data stack update, not data stack!!!

**Comment by dxxxxy** [comment]
> You changed data stack.
> You need to chamge data stack update, not data stack!!!

oh crap, i did not pay attention to that, do you have the old characterdatastack sig so i can replace it?

**Comment by dxxxxy** [comment]
nvm i got it ill go try it out right now

**Comment by codexJoin** [comment]
Restore your character data stack to original: "8D 8E ? ? ? ? FF 74 24 4C"
and change these again:

SkinID: 80 BE ? ? ? ? ? 75 4D 0F 31 33 C9 66 C7 86 ? ? ? ? ? ? 89 44 24 18 33 FF
CharacterDataStack_Update = 83 EC 2C 53 56 57 8D 44 24 28

https://i.imgur.com/xhKJ8gq.png
https://i.imgur.com/oz6XlT3.png

**Comment by dxxxxy** [comment]
> Restore your character data stack to original: "8D 8E ? ? ? ? FF 74 24 4C"
> and change these again:
> 
> SkinID: 80 BE ? ? ? ? ? 75 4D 0F 31 33 C9 66 C7 86 ? ? ? ? ? ? 89 44 24 18 33 FF
> CharacterDataStack_Update = 83 EC 2C 53 56 57 8D 44 24 28
> 
> https://i.imgur.com/xhKJ8gq.png
> https://i.imgur.com/oz6XlT3.png

it works flawlessly thank you! appreciate the support for such a dumb mistake haha
