### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by zelinux0202** [B3akers/LeagueSkinChanger#12]
I'm new to coding and such and I really wanted a open source alternative for league skin changer. Can anyone help me compile this? I've spent 4 hours trying many different tutorials and ways to compile and couldn't do it.

**Comment by nnk97** [comment]
It's ready to compile in Visual Studio, just pick "Release" and "x86" configurations on top and it will all build fine.
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
