### ISSUE TITLE
how to find Riot__Renderer__MaterialRegistry__GetSingletonPtr with cheatengine?

### ISSUE THREAD

**Issue by weituotian** [B3akers/LeagueSkinChanger#19]
if league update, i must update the value of Riot__Renderer__MaterialRegistry__GetSingletonPtr?

may  there is a tutorial to find the base address of League by cheatengine

**Comment by souregi** [comment]
did you figure out ?

**Comment by B3akers** [comment]
you can use pattern scanning, signature is in "autoupdater.cpp"
