### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by Igor-Imej** [B3akers/LeagueSkinChanger#20]
If anyone can explain how can I use this skin changer or if there is any tutorial

**Comment by SterlingSilber** [comment]
download release, open .exe, start game, press paste.

**Comment by Igor-Imej** [comment]
yeah I got Injected sucessfully! massage but what should I do now

**Comment by Kittylxz** [comment]
>Download Release
>Open injector while start a match
>press Insert to open menú
>Enjoy :)

**Comment by Igor-Imej** [comment]
Thanks

**Comment by Igor-Imej** [comment]
ok I got new problem when I press insert nothing happens idk why I managed to use it once in practice tool still gives injected successfully message but nothing happens when I press insert
