### ISSUE TITLE
How does it work internally ?

### ISSUE THREAD

**Issue by souregi** [B3akers/LeagueSkinChanger#26]
I am not a c++ developer (I work with c#), I want to make a pbe wad file that contains a new skin work on normal server, I tried to mix leagueSkinchanger with Lolcustomskin to change wad file. It did not work, I also tried to manually change copy/replace wad file it did not work either. How does it work ? where do you read the skin list for a certain champion ? is it from game.db ? or from the wad itself ? I am curious

**Comment by B3akers** [comment]
Skin list are from Global/Champions/championskins.info in Global.wad.client
