### ISSUE TITLE
So many skins bugged

### ISSUE THREAD

**Issue by amir2204musin** [B3akers/LeagueSkinChanger#28]
this soft is bad because many skin i would like to use are bugged

**Comment by souregi** [comment]
The software itself is excellent and it can go so far, but the developer does not give any feedback and the app does not work anymore on PBE after this last league release, which means it will no more work after next release on normal servers. I mean why putting so much effort on something and then give up on the last step! I wish I could understand c++. I am a c# programer :(

**Comment by amir2204musin** [comment]
> The software itself is excellent and it can go so far, but the developer does not give any feedback and the app does not work anymore on PBE after this last league release, which means it will no more work after next release on normal servers. I mean why putting so much effort on something and then give up on the last step! I wish I could understand c++. I am a c# programer :(

this is evolve of league skin program, these skins bugged there to

**Comment by B3akers** [comment]
These software has auto update which depends on pattern scanning, most of cases it should work if new version of league of legends released but also there is a chance that one sig will be broken then i have to fix it manually
