### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TorontoToky0** [B3akers/LeagueSkinChanger#30]
the game crashes with an injection, when connected, the game crashes again. what to do?

**Comment by PythonTryHard** [comment]
Assuming you're on `10.25`, have the injector opened (optional with admin privilege for some regions' client) right from the beginning, the game will crash even if you do nothing. The workaround is wait until the game fully loaded, you are in the arena, only then run the injector. See PR #29, quote:
> only works, when injecting whilst already being ingame btw ^^

**Comment by B3akers** [comment]
Which server, champion?

**Comment by TorontoToky0** [comment]
Russian. Ahri, Fiddl, Kata.  These are the heroes I played when I tried to use the skin changer.
