### ISSUE TITLE
Injection success, but IMGUI is missing

### ISSUE THREAD

**Issue by CreativeHell** [B3akers/LeagueSkinChanger#34]
i believe that due to the league's recent update they changed some offsets or similar. since now, it wont bring up the menu but the injection is successful.

**Issue:**
Injection successful, but IMGUI is not injected or won't show up.

**Guess everyone agrees with this.**

**Comment by 6oody** [comment]
same issuse with me but i think he said he don't know how to solve the issuse in this moment

**Comment by Clownsw** [comment]
[](https://img.imgdb.cn/item/5ffa82113ffa7d37b337ba5c.png)

**Comment by Clownsw** [comment]
![QQ截图20210110121428](https://user-images.githubusercontent.com/28394742/104114428-4fb15980-533f-11eb-9ad1-966b8b2c6af9.png)

**Comment by Kittylxz** [comment]
I have the same issue, we have to wait i guess he patch again:(

**Comment by AizWho** [comment]
Same.

**Comment by 6oody** [comment]
> I have the same issue, we have to wait i guess he patch again:(

:( i hate the another lol skin i don't wanna use it and i'm just waiting them to fix it
