### ISSUE TITLE
Adding Mapskins?

### ISSUE THREAD

**Issue by PrincessAkira** [B3akers/LeagueSkinChanger#5]
Is it possible to add MapSkins?
Since on CustomSkins, Rifts like Bloodmoon, arent Usable due to different file stuff etc etc

**Comment by PrincessAkira** [comment]
If it isnt possible just close this 👍🏻

**Comment by B3akers** [comment]
It is possible, i will try to add in future.

**Comment by PrincessAkira** [comment]
Quick question 

Would recall Anims and Languages and Announcers be possible too?

Announcerd and Language im sure but idk about Recalls
