### ISSUE TITLE
How to add fonts

### ISSUE THREAD

**Issue by AbrnYa** [B3akers/LeagueSkinChanger#59]
![image](https://user-images.githubusercontent.com/77602247/116836143-063f8f80-abf8-11eb-82c7-5e7d8d1e6115.png)

**Comment by AbrnYa** [comment]
Chinese becomes a question mark

**Comment by Aperodry** [comment]
you need use AddFontFromFileTTF() to support CN

**Comment by AbrnYa** [comment]
> 您需要使用附加功能从档案（）来支持CN

Which file should I add to?

**Comment by Aperodry** [comment]
in init_imgui()，which need change at get_system_font_path( "Courier", font_path )

**Comment by AbrnYa** [comment]
> in init_imgui()，which need change at get_system_font_path( "Courier", font_path )

You are wonderful. Thank you very much for your help
