### ISSUE TITLE
Not working after patch 11.10

### ISSUE THREAD

**Issue by ForsenFanboy** [B3akers/LeagueSkinChanger#63]
injector says its injected but its not working ingame. after restarting injector it only gives msg about looking for processes. i think its not only mine problem ;) (i tried reinstalling, turing off my antivirus and giving it Administrator privilege.)

**Comment by codexJoin** [comment]
Just update ChampionManager Signature and IsLaneMinion signature xD

**Comment by superchedder** [comment]
> Just update ChampionManager Signature and IsLaneMinion signature xD

Could you please explain how you can do that ?

**Comment by Kittylxz** [comment]
> Just update ChampionManager Signature and IsLaneMinion signature xD

How i can do that? O.o
