### ISSUE TITLE
Doesn't work on 11.11

### ISSUE THREAD

**Issue by Shweep80** [B3akers/LeagueSkinChanger#79]

**Comment by enescglyn** [comment]
fixed download new version

**Comment by Shweep80** [comment]
> fixed download new version

Thanks!

**Comment by Shweep80** [comment]
> fixed download new version

Wait how do I open the injector with the update? Before it was just an exe file. Do i need to manually inject it now?

**Comment by Aesthesys** [comment]
> Wait how do I open the injector with the update? Before it was just an exe file. Do i need to manually inject it now?

It is still an .exe file, just download the new version from the release page.

**Comment by Shweep80** [comment]
> > Wait how do I open the injector with the update? Before it was just an exe file. Do i need to manually inject it now?
> 
> It is still an .exe file, just download the new version from the release page.

oh my god im sorry i accidentally downloaded the source code. thanks for fixing the skin changer!
