### ISSUE TITLE
Why have a virus?

### ISSUE THREAD

**Issue by ATrollWithAClub** [B3akers/LeagueSkinChanger#82]
![image](https://user-images.githubusercontent.com/84552468/120069084-0cd3f200-c052-11eb-8075-6cc3e384b126.png)

**Comment by FedeArre** [comment]
This is literally a DLL Injector, what you expected? Is obvious that an anti-virus would detect it as virus, but is not. Please read the source code of the injector if you don't believe me.

**Comment by ATrollWithAClub** [comment]
I only said that how can I do so that this alert does not appear every time and the program is not eliminated :c

**Comment by FedeArre** [comment]
> I only said that how can I do so that this alert does not appear every time and the program is not eliminated :c

Read the post you wrote, you didn't say that.
You should not disable your antivirus, only create an exception for the software to run. [Guide of how to do it using Windows Defender](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#:~:text=Go%20to%20Start%20%3E%20Settings%20%3E%20Update,%2C%20file%20types%2C%20or%20process.).

**Comment by ATrollWithAClub** [comment]
Thanksssssssssss I love u <3
