### ISSUE TITLE
Crash after injecting

### ISSUE THREAD

**Issue by krukuhehe** [B3akers/LeagueSkinChanger#96]
Problem as it says on title,

**Comment by enescglyn** [comment]
does it happen everytime you use it or rarely it crashes rarely on mine too but they happen really rare

**Comment by krukuhehe** [comment]
Maybe it was just a problem xd

**Comment by enescglyn** [comment]
i take my word back when i use it it freezes game after playing for like 5 mins

**Comment by Amaren1** [comment]
yes it makes my game crash sometimes, i wouldnt recomend using it
